# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
    publish = "example/build/"
    command = "cd example && yarn && yarn build"
